/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const storeProducts = [
  {
    id: 1,
    title: "Deby/Oxfoert-black-shoe ",
    img: "img/product-1.jpg",
    price: 300,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Lafer black-shoe",
    img: "img/product-2.jpg",
    price: 250,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Plafform black-shoe",
    img: "img/product-3.jpg",
    price: 300,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Women Ostrich Handbag Fashion Ladies Shoulder Bag Top Handle Satchel Purse",
    img: "img/product-4.jpg",
    price: 320,
    company: "Women Ostrich Handbag Fashion Ladies Shoulder Bag Top Handle Satchel Purse",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Top Handle Satchel Shoulder Tote Bag ",
    img: "img/product-5.jpg",
    price: 400,
    company: "skywear",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title:" Classy Satchel Handbag Tote Purse Handle Bag Shoulder Bag",
    img: "img/product-6.jpg",
    price: 370,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Mazzamax Womens Purses and Handbags Ladies Designer Satchel Tote Bag Shoulder Bags",
    img: "img/product-7.jpg",
    price: 250,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Brown & white long sleeve shirt",
    img: "img/product-8.jpg",
    price: 150,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Deby/Oxfoert-black-shoe ",
    img: "img/product-1.jpg",
    price: 300,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Lafer black-shoe",
    img: "img/product-2.jpg",
    price: 250,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Plafform black-shoe",
    img: "img/product-3.jpg",
    price: 300,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 12,
    title: "Handbag",
    img: "img/product-5.jpg",
    price: 400,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "Handbag mix-color",
    img: "img/product-6.jpg",
    price: 370,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Handbag red-color",
    img: "img/product-7.jpg",
    price: 250,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "Shirt mix-color",
    img: "img/product-8.jpg",
    price: 150,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: "Oxfort black shoe",
    img: "img/product-1.jpg",
    price: 300,
    company: "Abmazak",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id:17,
    title:"men shirt",
     imag:"img/product-17.jpg",
     price:200,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:18,
    title:"Shoppers products",
     img:"img/product-18.jpg",
     price:3000, 
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false, 
       count: 0,
        total:0,
  },
  {
    id:19,
    title:"ladies shorthand dress", 
    img:"img/product-19.jpeg",
    price:100, 
    company:"Abmazak",
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:20,
    title:" One hand dress",
     img:"img/product-20.jpg",
    price:150,
     company:"Amazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", inCart: false, count: 0, total:0,
  },
  {
    id:21,
    title:"Ladies dress",
     imag:"img/product-21.webp",
     price:200,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:22,
    title:"kids dress",
     img:"img/product-22.jpeg",
     price:120,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:23,
    title:"kids dress",
     img:"img/product-23.jpeg",
     price:100,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart: false,
         count: 0,
          total:0,
  },
  {
    id:24,
    title:"Ladies dress",
     img:"img/product-24.webp",
     price:200, 
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:25,
    title:"ladies wristwatch",
     img:"img/product-25.jpg",
     price:300,
      company:"Abmazak", info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:26,
    title:"Wrist watch for men",
     img:"img/product-26.jpeg",
     price:350,
      company:"Abazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:27,
    title:"Wrist watch for men",
     img:"img/product-27.jpeg",
     price:400,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart: false,
         count: 0,
          total:0,
  },
  {
    id:28,
    title:"Wrist watch for men", 
    img:"img/product-28.jpeg",
    price:360, 
    company:"Abmazak",
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:29,
    title:"Wrist watch for men", 
    img:"img/product-29.jpeg",
    price:400,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:30,
    title:"Wrist watch for men",
     img:"img/product-30.jpeg",
     price:200,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart: false,
         count: 0,
          total:0,
  },
  {
    id:31,
    title:"Smart phone",
     img:"img/product-31.jpeg",
     price:1000,
      company:"Abmazak", 
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:32,
    title:"Iphone",
     img:"img/product-32.jpeg",
     price:3700,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart: false,
         count: 0,
          total:0,
  },
  {
    id:33,
    title:"Itel", 
    img:"img/product-33.jpeg",
    price:2500,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:34,
    title:"Iphone", 
    img:"img/product-34.jpeg",
    price:5000,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:35,
    title:"Nokia", 
    img:"img/product-35.jpeg",
    price:4000,
     company:"Amazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false, 
       count: 0,
        total:0,
  },
  {
    id:36,
    title:"Tecno", 
    img:"img/product-36.jpeg",
    price:2500, 
    company:"Abmazak",
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:37,
    title:"Tecno", 
    img:"img/product-37.jpeg",
    price:2000,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:38,
    title:"Motorolla", 
    img:"img/product-38.jpeg",
    price:1700,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:39,
    title:"Tecno", 
    img:"img/product-39.jpeg",
    price:2700,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  
  {
    id:41,
    title:"Headset black color",
     img:"img/product-41.jpg",
     price:150, 
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:42,
    title:"Headset sizable black color",
     img:"img/product-42.jpeg",
     price:400,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart:
         false,
          count: 0, 
     total:0,
  },
  {
    id:43,
    title:"Headset sizable black color",
     img:"img/product-43.jpg",
     price:250, 
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:44,
    title:"Headset black color", 
    img:"img/product-44.jpeg",
    price:200,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:45,
    title:"Headset white color",
     img:"img/product-45.jpeg",
     price:220,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart: false,
         count: 0,
          total:0,
  },
  {
    id:46,
    title:"Headset teal colr",
     img:"img/product-46.jpeg",
    price:250, 
    company:"Abmazak",
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0, 
       total:0,
  },
  {
    id:47,
    title:"Headset smallsize black color",
     img:"img/product-47.jpeg",
     price:200,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false, 
      count: 0,
       total:0,
  },
  {
    id:48,
    title:"Headset black color",
     img:"img/product-48.jpeg",
     price:170,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
       inCart: false,
        count: 0, 
        total:0,
  },
  {
    id:49,
    title:"Headset color pink",
     img:"img/product-49.jpeg",
     price:150, 
     company:"Amazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:50,
    title:"Headset mix color redand teal", 
    img:"img/product-50.jpeg",
    price: 100, 
    company:"Abmazak",
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
     inCart: false,
      count: 0,
       total:0,
  },
  {
    id:51,
    title:"Double doors fridge",
     img:"img/product-51.jpg",
     price:5500,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart: false, 
        count: 0, 
        total:0,
  },
  {
    id:52,
    title:"Double deckerStand fridge", 
    img:"img/product-52.jpg",
    price:5000,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
      inCart: false, 
      count: 0,
       total:0,
  },
  {
    id:53,
    title:"Mac/Apple",
     img:"img/product-53.jpg",
    price:6000,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
      inCart: false,
       count: 0, 
       total:0,
  },
  {
    id:54,
    title:"Hp", 
    img:"img/product-54.jpeg",
    price:6000, 
    company:"Abmazak",
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:55,
    title:"Hp",
     img:"img/product-55.jpeg",
    price:7000,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
       count: 0,
        total:0,
  },
  {
    id:56,
    title:"Thinkpad",
     img:"img/product-56.jpeg",
     price:6000,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart: false,
         count: 0,
          total:0,
  },
  {
    id:57,
    title:"Thinkpad", 
    img:"img/product-57.jpeg",
    price:7000,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:58,
    title:"Acer", 
    img:"img/product-58.jpeg",
    price:5000,
     company:"Abmazak",
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false, 
      count: 0, 
      total:0,
  },
  {
    id:59,
    title:"Mac/Apple",
    img:"img/product-59.jpg",
    price:7000,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false, 
      count: 0,
       total:0,
  },
  {
    id:60,
    title:"Iphone",
     img:"img/product-60.jpg",
    price:4000, 
    company:"Abmazak",
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
     inCart: false,
      count: 0, 
      total:0,
  },
  {
    id:61,
    title:"nokia",
     img:"img/product-61.jpg",
    price:2500,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
      inCart: false,
       count: 0, 
       total:0,
  },
  {
    id:62,
    title:"Itel", 
    img:"img/product-62.jpg",
    price:1200,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0, 
        total:0,
  },
  {
    id:63,
    title:"Huawei", 
    img:"img/product-63.jpg",
    price:3000,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:64,
    title:"Nokia",
     img:"img/product-64.jpeg",
     price:2500,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
       inCart: false, 
       count: 0, 
       total:0,
  },
  {
    id:65,
    title:"Tecne Cammon", 
    img:"img/product-65.jpeg",
    price:2000,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0, 
        total:0,
  },
  {
    id:66,
    title:"Itel", 
    img:"img/product-66.jpeg",
    price:1500,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:67,
    title:"Tecno", 
    img:"img/product-67.jpeg",
    price:1000,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:68,
    title:"women footwear",
     img:"img/product-68.jpeg",
     price:150,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
        inCart: false,
         count: 0, 
         total:0,
  },
  {
    id:69,
    title:"HighHillwear", 
    img:"img/product-69.jpeg",
    price:300,
     company:"Abmzak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:70,
    title:"Ladies waer",
     img:"img/product-70.jpg",
     price:250,
      company:"Abmazak", 
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false, 
       count: 0,
        total:0,
  },
  {
    id:71,
    title:"Ladies footwear",
     img:"img/product-71.jpg",
     price:200, 
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
      inCart: false, 
      count: 0,
  },    
  {
    id:72,
    title:"HighHill for ladies", 
    img:"img/product-72.jpg",
    price:300,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:73,
    title:"Casual footwear", 
    img:"img/product-73.jpg",
    price:250,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
      inCart: false, 
      count: 0,
       total:0,
  },
  {
    id:74,
    title:"Nike footwear", 
    img:"img/product-74.jpeg",
    price:350,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:75,
    title:"Yellow corn-flour",
     img:"img/product-75.jpeg",
     price:60, 
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:76,
    title:"Gunea corn flour", 
    img:"img/product-76.jpg",
    price:70,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:77,
    title:"Agoshie flour", 
    img:"img/product-77.jpeg",
    price:90,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0,
        total:0,
  },
  {
    id:78,
    title:"White corn-flour", 
    img:"img/product-78.jpeg",
    price:40,
     company:"Abmazak",
      info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:79,
    title:"Millet-flour",
     img:"img/product-79.jpeg",
     price:80,
      company:"Abmazak",
       info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results", 
       inCart: false,
        count: 0,
         total:0,
  },
  {
    id:80,
    title:"Soyabean-flour",
     img:"img/product-80.jpeg",
    price:60,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false,
       count: 0, 
       total:0,
  },
  {
    id:81,
    title:"Cassava flour", 
    img:"img/product-81.jpeg",
    price:50,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false, 
     count: 0, 
     total:0,
  },
  {
    id:82,
    title:"yellow-corn", 
    img:"img/product-82.jpeg",
    price:60,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false, 
     count: 0, 
     total:0,
  },
  {
    id:83,
    title:"Dawadawa", 
    img:"img/product-83.jpg",
    price:70,
     company:"Abmazak", 
     info: "Find Best Product Marketing Strategies. Now with us! Search For Best Product Marketing Strategies at findresultsnow.co. Awesome Info. Latest Today. Fast Response. More Info. Get Latest Info. Updated Info. Get More Results. Attractive Results. Relevant Results",
      inCart: false, 
     count: 0, 
     total:0,
  },
 
  

];

export const detailProduct = {
  id: 1,
  title: "round-neck long-sleeve blue ",
  img: "img/product-1.jpg",
  price: 40,
  company: "skywears",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
